#include "GamePlayTags/TestTags.h"

namespace Test {
	namespace TestTag {
		UE_DEFINE_GAMEPLAY_TAG(Primordia::TestTag::Root, "Test.TestTag");
	}
	namespace Stats {
		UE_DEFINE_GAMEPLAY_TAG(Primordia::PrimaryStats::Root, "Primordia.PrimaryStats");
		namespace Combat {
			UE_DEFINE_GAMEPLAY_TAG(Primordia::PrimaryStats::Root, "Primordia.PrimaryStats");

		}
		namespace Player { // 재화
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(돈);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(식량);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(마나?);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(조각?);

		}
	}

	namespace 몹들 ? {
		namespace 아군들 ? {
			????
		}
		namespace 적군들 ? {

		}
	}

	namespace Item {
		DATAINFO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);
		namespace Set {
			namespace 탈라샤 {
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(갑빠);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(무기);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(대가리);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(부츠);
			}
			namespace 뭐든 {
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(갑빠);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(무기);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(대가리);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(부츠);
			}
		}
		namespace 단일 {
			namespace 무기 {
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(검);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(목검);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(철검);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(뭐시기검);
			}
			namespace 갑빠 {
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(갑빠);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(목갑빠);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(철갑빠);
				TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(뭐시기갑빠);
			}
		}
	}

	namespace Skill {
		namespace SkillID {
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(슬로우);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(기절확률오오라);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(휘두르기);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(출혈확률오오라);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(메테오);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(오라?);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(??);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(스킬);
		}
		namespace SkillType {
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Active);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(오로라);
			TEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(궁극기?);
		}
	}

	
}